baseURL = "https://sharukhi.net"
theme = 'hugo-bearblog'
title = "Sharukhi"
author = "Sharukhi"
copyright = "Copyright © Sharukhi."
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
[params]
  description = "Sharukhi"
  favicon = "images/favicon.ico"
  images = ["images/og.png"]
  title = "Sharukhi"
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
